#!/usr/bin/env python
"""
Script to run tests from the source checkout
"""
import os
import sys

pkgdir = os.path.join(os.path.dirname(__file__), 'src')
sys.path.insert(0, pkgdir)

from iptools.test_iptools import main
main()
